version: "3.9"

services:
  db:
    image: postgres
    container_name: basket.db
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  web:
    build: .
    container_name: basket.web
    command: ["./entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    # entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  data:
    driver: local