version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  data:
    driver: local